import { CardRank, HandType, HandRange, CARD_RANKS, RANK_ORDER } from './types';

// 169 starting hands bucketed by cumulative top-X% strength. Generated by
// scripts/gen-hand-rankings.mjs from a seeded (mulberry32(42)) Monte Carlo
// simulation of each hand's equity vs a uniformly random opponent hand on a
// uniformly random 5-card board (300k trials/hand), ranked descending and
// bucketed by walking cumulative combo counts (pair=6, suited=4, offsuit=12)
// against fixed target boundaries. Re-run the script to reproduce.
// Each bucket label corresponds to its cumulative threshold; empty bucket falls through to '60-70%'.
export const HAND_RANGE_MAP: Record<string, HandRange> = {
  'AA':'3%','KK':'3%','QQ':'3%','JJ':'3%','TT':'3%',
  '99':'5%','88':'5%','AKs':'5%','77':'5%','AQs':'5%',
  'AJs':'8%','AKo':'8%','ATs':'8%','AQo':'8%','AJo':'8%','KQs':'8%',
  '66':'10%','A9s':'10%','ATo':'10%','KJs':'10%',
  'A8s':'12-15%','KTs':'12-15%','KQo':'12-15%','A7s':'12-15%','A9o':'12-15%','KJo':'12-15%','QJs':'12-15%','55':'12-15%',
  'A6s':'18-20%','A5s':'18-20%','K9s':'18-20%','KTo':'18-20%','A8o':'18-20%','QTs':'18-20%','A4s':'18-20%','A7o':'18-20%','A3s':'18-20%','QJo':'18-20%','K8s':'18-20%',
  'K9o':'25%','A5o':'25%','K7s':'25%','A6o':'25%','Q9s':'25%','A2s':'25%','JTs':'25%','QTo':'25%',
  '44':'30-35%','K6s':'30-35%','A4o':'30-35%','K8o':'30-35%','Q8s':'30-35%','K5s':'30-35%','A3o':'30-35%','J9s':'30-35%','JTo':'30-35%','K7o':'30-35%','Q9o':'30-35%','A2o':'30-35%','K4s':'30-35%','Q7s':'30-35%','K6o':'30-35%','J8s':'30-35%','K3s':'30-35%',
  'T9s':'40-45%','33':'40-45%','Q6s':'40-45%','Q8o':'40-45%','J9o':'40-45%','K5o':'40-45%','K2s':'40-45%','Q5s':'40-45%','J7s':'40-45%','K4o':'40-45%','T8s':'40-45%','Q4s':'40-45%','Q7o':'40-45%','K3o':'40-45%','J8o':'40-45%','T9o':'40-45%',
  'Q6o':'50%','Q3s':'50%','98s':'50%','K2o':'50%','T7s':'50%','J6s':'50%','22':'50%','Q2s':'50%','Q5o':'50%',
  'J5s':'60-70%','T8o':'60-70%','J7o':'60-70%','97s':'60-70%','Q4o':'60-70%','J4s':'60-70%','T6s':'60-70%','Q3o':'60-70%','J3s':'60-70%','98o':'60-70%','87s':'60-70%','T7o':'60-70%','J6o':'60-70%','J2s':'60-70%','96s':'60-70%','Q2o':'60-70%','J5o':'60-70%','T5s':'60-70%','T4s':'60-70%','97o':'60-70%','J4o':'60-70%','86s':'60-70%','T6o':'60-70%','95s':'60-70%','T3s':'60-70%','J3o':'60-70%','76s':'60-70%','87o':'60-70%','T2s':'60-70%','85s':'60-70%','96o':'60-70%','J2o':'60-70%','T5o':'60-70%','94s':'60-70%','75s':'60-70%','T4o':'60-70%','93s':'60-70%','86o':'60-70%','65s':'60-70%','84s':'60-70%','95o':'60-70%','T3o':'60-70%','92s':'60-70%','76o':'60-70%','74s':'60-70%','T2o':'60-70%','54s':'60-70%','85o':'60-70%','64s':'60-70%','83s':'60-70%','94o':'60-70%','75o':'60-70%','82s':'60-70%','93o':'60-70%','65o':'60-70%','73s':'60-70%','53s':'60-70%','63s':'60-70%','84o':'60-70%','92o':'60-70%','43s':'60-70%','74o':'60-70%','72s':'60-70%','54o':'60-70%','64o':'60-70%','52s':'60-70%','62s':'60-70%','83o':'60-70%','82o':'60-70%','42s':'60-70%','73o':'60-70%','63o':'60-70%','53o':'60-70%','32s':'60-70%','43o':'60-70%','72o':'60-70%','52o':'60-70%','62o':'60-70%','42o':'60-70%','32o':'60-70%',
};

export function getHandRange(card1: CardRank, card2: CardRank, handType: HandType): HandRange {
  return HAND_RANGE_MAP[handNotation(card1, card2, handType)] || '60-70%';
}

export const TOTAL_COMBOS = 1326;
export const BUCKET_WEIGHTS: Record<HandRange, number> = (() => {
  const w = {} as Record<HandRange, number>;
  for (const r of CARD_RANKS) {
    const b = getHandRange(r, r, 'pair');
    w[b] = (w[b] || 0) + 6;
  }
  for (let i = 0; i < CARD_RANKS.length; i++) {
    for (let j = i + 1; j < CARD_RANKS.length; j++) {
      const a = CARD_RANKS[i], b = CARD_RANKS[j];
      const s = getHandRange(a, b, 'suited');
      w[s] = (w[s] || 0) + 4;
      const o = getHandRange(a, b, 'offsuit');
      w[o] = (w[o] || 0) + 12;
    }
  }
  return w;
})();

export function formatExpected(n: number): string {
  return n >= 10 ? Math.round(n).toString() : n.toFixed(1);
}

export function handNotation(card1: CardRank, card2: CardRank, handType: HandType): string {
  const [higher, lower] = RANK_ORDER[card1] >= RANK_ORDER[card2] ? [card1, card2] : [card2, card1];
  const suffix = handType === 'pair' ? '' : handType === 'suited' ? 's' : 'o';
  return `${higher}${lower}${suffix}`;
}
